"""
Security Test Generator
Generates security regression tests from Bob's analysis
"""

import os
import logging
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime

logger = logging.getLogger(__name__)


class TestGenerator:
    """Generates security tests from incident analysis"""
    
    def __init__(self, config: Dict[str, Any]):
        """
        Initialize test generator
        
        Args:
            config: Test generation configuration
        """
        self.config = config
        self.output_dir = Path(config.get('output_directory', './generated_tests'))
        self.test_framework = config.get('test_framework', 'pytest')
        
        # Create output directory
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_tests_from_bob_output(self, 
                                       bob_output: Dict[str, Any], 
                                       incident: Dict[str, Any]) -> List[str]:
        """
        Generate security tests from Bob's analysis
        
        Args:
            bob_output: Bob's output with generated_security_tests
            incident: Original incident data
            
        Returns:
            List of generated test file paths
        """
        generated_tests = bob_output.get('generated_security_tests', [])
        
        if not generated_tests:
            logger.warning("No security tests in Bob output")
            return []
        
        test_files = []
        
        for test_spec in generated_tests:
            try:
                file_path = self._generate_test_file(test_spec, incident)
                if file_path:
                    test_files.append(file_path)
            except Exception as e:
                logger.error(f"Failed to generate test {test_spec.get('name', 'unknown')}: {str(e)}")
        
        logger.info(f"Generated {len(test_files)} test files")
        return test_files
    
    def _generate_test_file(self, test_spec: Dict[str, Any], incident: Dict[str, Any]) -> str:
        """Generate a single test file"""
        file_name = test_spec.get('file', 'test_security.py')
        test_name = test_spec.get('name', 'test_security')
        purpose = test_spec.get('purpose', 'Security test')
        code = test_spec.get('code', '')
        
        # Ensure file name is valid
        if not file_name.endswith('.py'):
            file_name = f"{file_name}.py"
        
        # Create full path
        file_path = self.output_dir / file_name
        
        # Check if file already exists
        if file_path.exists():
            # Append to existing file
            return self._append_to_test_file(file_path, test_spec, incident)
        else:
            # Create new file
            return self._create_test_file(file_path, test_spec, incident)
    
    def _create_test_file(self, 
                         file_path: Path, 
                         test_spec: Dict[str, Any], 
                         incident: Dict[str, Any]) -> str:
        """Create a new test file"""
        incident_id = incident.get('incident_id', 'INC-UNKNOWN')
        test_name = test_spec.get('name', 'test_security')
        purpose = test_spec.get('purpose', 'Security test')
        code = test_spec.get('code', '')
        
        # Build test file content
        content = f'''"""
Security Tests for Incident {incident_id}
Generated by IBM Jeff
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""

import pytest


# {purpose}
{code}


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''
        
        # Write file
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        logger.info(f"Created test file: {file_path}")
        return str(file_path)
    
    def _append_to_test_file(self, 
                            file_path: Path, 
                            test_spec: Dict[str, Any], 
                            incident: Dict[str, Any]) -> str:
        """Append test to existing file"""
        incident_id = incident.get('incident_id', 'INC-UNKNOWN')
        test_name = test_spec.get('name', 'test_security')
        purpose = test_spec.get('purpose', 'Security test')
        code = test_spec.get('code', '')
        
        # Read existing content
        with open(file_path, 'r', encoding='utf-8') as f:
            existing_content = f.read()
        
        # Check if test already exists
        if test_name in existing_content:
            logger.info(f"Test {test_name} already exists in {file_path}")
            return str(file_path)
        
        # Append new test
        new_test = f'''

# {purpose} (Incident {incident_id})
{code}
'''
        
        # Insert before the if __name__ block
        if 'if __name__ == "__main__":' in existing_content:
            parts = existing_content.split('if __name__ == "__main__":')
            updated_content = parts[0] + new_test + '\n\nif __name__ == "__main__":' + parts[1]
        else:
            updated_content = existing_content + new_test
        
        # Write updated content
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(updated_content)
        
        logger.info(f"Appended test to: {file_path}")
        return str(file_path)
    
    def generate_test_suite(self, incidents: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Generate complete test suite from multiple incidents
        
        Args:
            incidents: List of incidents with Bob analysis
            
        Returns:
            Summary of generated tests
        """
        all_test_files = []
        test_count = 0
        
        for incident in incidents:
            bob_analysis = incident.get('bob_analysis', {})
            if bob_analysis:
                test_files = self.generate_tests_from_bob_output(bob_analysis, incident)
                all_test_files.extend(test_files)
                test_count += len(bob_analysis.get('generated_security_tests', []))
        
        # Generate test suite runner
        suite_file = self._generate_suite_runner(all_test_files)
        
        return {
            'test_files': list(set(all_test_files)),
            'test_count': test_count,
            'suite_runner': suite_file,
            'output_directory': str(self.output_dir)
        }
    
    def _generate_suite_runner(self, test_files: List[str]) -> str:
        """Generate a test suite runner"""
        runner_path = self.output_dir / 'run_security_tests.py'
        
        content = f'''"""
Security Test Suite Runner
Generated by IBM Jeff
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""

import pytest
import sys
from pathlib import Path


def run_security_tests():
    """Run all generated security tests"""
    test_dir = Path(__file__).parent
    
    # Run pytest with verbose output
    exit_code = pytest.main([
        str(test_dir),
        "-v",
        "--tb=short",
        "-x",  # Stop on first failure
        "--color=yes"
    ])
    
    return exit_code


if __name__ == "__main__":
    print("=" * 60)
    print("Running Security Test Suite")
    print("=" * 60)
    
    exit_code = run_security_tests()
    
    if exit_code == 0:
        print("\\n✓ All security tests passed!")
    else:
        print(f"\\n✗ Security tests failed with exit code: {{exit_code}}")
    
    sys.exit(exit_code)
'''
        
        with open(runner_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        logger.info(f"Created test suite runner: {runner_path}")
        return str(runner_path)
    
    def generate_readme(self, test_summary: Dict[str, Any]) -> str:
        """Generate README for generated tests"""
        readme_path = self.output_dir / 'README.md'
        
        content = f'''# Generated Security Tests

**Generated by IBM Jeff**  
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Overview

This directory contains security regression tests generated from incident analysis.

## Test Summary

- **Total Tests:** {test_summary.get('test_count', 0)}
- **Test Files:** {len(test_summary.get('test_files', []))}

## Test Files

'''
        
        for test_file in test_summary.get('test_files', []):
            file_name = Path(test_file).name
            content += f"- `{file_name}`\n"
        
        content += f'''
## Running Tests

### Run All Tests

```bash
python run_security_tests.py
```

### Run Specific Test File

```bash
pytest {test_summary.get('test_files', ['test_security.py'])[0] if test_summary.get('test_files') else 'test_security.py'} -v
```

### Run with Coverage

```bash
pytest --cov=. --cov-report=html
```

## Integration with CI/CD

Add these tests to your CI/CD pipeline:

```yaml
# .github/workflows/security-tests.yml
name: Security Tests

on: [push, pull_request]

jobs:
  security-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Run security tests
        run: |
          cd generated_tests
          python run_security_tests.py
```

## Notes

- These tests are generated based on security incident analysis
- Review and customize tests as needed for your specific environment
- Add these tests to your regular test suite
- Update tests when security policies change

---
*Generated by IBM Jeff*
'''
        
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        logger.info(f"Created README: {readme_path}")
        return str(readme_path)


# Made with Bob