"""
Security Test Suite Runner
Generated by IBM Bob Sentinel
Date: 2026-05-16 14:24:41
"""

import pytest
import sys
from pathlib import Path


def run_security_tests():
    """Run all generated security tests"""
    test_dir = Path(__file__).parent
    
    # Run pytest with verbose output
    exit_code = pytest.main([
        str(test_dir),
        "-v",
        "--tb=short",
        "-x",  # Stop on first failure
        "--color=yes"
    ])
    
    return exit_code


if __name__ == "__main__":
    print("=" * 60)
    print("Running Security Test Suite")
    print("=" * 60)
    
    exit_code = run_security_tests()
    
    if exit_code == 0:
        print("\n✓ All security tests passed!")
    else:
        print(f"\n✗ Security tests failed with exit code: {exit_code}")
    
    sys.exit(exit_code)
